language: php

php:
  - hhvm

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y hhvm-dev
  - git submodule update --init --recursive

install:
- sudo apt-get install -qq g++-4.9
- export CXX="g++-4.9"

script:
  - ./build.sh

notifications:
    on_success: never
    on_failure: never

os:
  - linux
