language: php

php:
  - hhvm

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - git submodule update --init --recursive

install:
- sudo apt-get install -qq g++-4.9
- sudo apt-get install -qq hhvm-dev
- sudo apt-get install -qq libboost1.55-all-dev
- wget http://caml.inria.fr/pub/distrib/ocaml-4.02/ocaml-4.02.1.tar.gz
- tar xvf ocaml-4.02.1.tar.gz
- cd ocaml-4.02.1
- ./configure
- make world.opt
- sudo make install
- export CXX="g++-4.9"

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ./build.sh

notifications:
    on_success: never
    on_failure: never

os:
  - linux
